const WEB_CLIENT_ID = process.env.EXPO_PUBLIC_WEB_CLIENT_ID;
const ANDROID_CLIENT_ID = process.env.EXPO_PUBLIC_ANDROID_CLIENT_ID;
const SCOPES = [process.env.EXPO_PUBLIC_SCOPES];
const SPREADSHEET_ID = process.env.EXPO_PUBLIC_SPREADSHEET_ID;

export { WEB_CLIENT_ID, ANDROID_CLIENT_ID, SCOPES, SPREADSHEET_ID };
