import {
  WEB_CLIENT_ID,
  ANDROID_CLIENT_ID,
  SCOPES,
  SPREADSHEET_ID,
  GET_SPREADSHEET_URL,
  EDIT_SPREADSHEET_URL,
} from "./config";
import { IS_MOCKED_ENABLED } from "./featureFlags";

export {
  WEB_CLIENT_ID,
  ANDROID_CLIENT_ID,
  SCOPES,
  SPREADSHEET_ID,
  IS_MOCKED_ENABLED,
  GET_SPREADSHEET_URL,
  EDIT_SPREADSHEET_URL,
};
